In [1]:
# 1.Write a Python program to create a tensor of shape (3, 3) filled with random numbers between 0 and 1.
#  Perform basic tensor operations including matrix addition, multiplication, and transpose.
#  Convert the resulting tensor into a NumPy array and then reshape it into a (1, 9) tensor. 

In [ ]:
import numpy as np
A = np.random.rand(3, 3)
print("Original Tensor (A):\n", A)

Original Tensor (A):
 [[0.26784382 0.32386595 0.30131269]
 [0.82047922 0.86067208 0.36899587]
 [0.43680897 0.58279774 0.74329253]]
<class 'numpy.ndarray'>


In [ ]:
B = A + A
print("Matrix Addition (A + A):\n", B)

Matrix Addition (A + A):
 [[1.23425759 1.50371347 0.20513288]
 [0.64418236 0.51555254 0.62724056]
 [1.93099823 1.74137012 0.77207211]]


In [ ]:
C = A @ A
print("Matrix Multiplication (A @ A):\n", C)

Matrix Multiplication (A @ A):
 [[0.72204218 0.74710633 0.33868857]
 [0.58459931 0.58167952 0.23494835]
 [1.24899475 1.28647478 0.52111614]]


In [ ]:
D = C.T
print("Transpose of Matrix (C.T):\n", D)

Transpose of Matrix (C.T):
 [[0.72204218 0.58459931 1.24899475]
 [0.74710633 0.58167952 1.28647478]
 [0.33868857 0.23494835 0.52111614]]


In [12]:
E= D.reshape(1, 9)
print("Reshaped Tensor (1, 9):\n", E)

Reshaped Tensor (1, 9):
 [[0.72204218 0.58459931 1.24899475 0.74710633 0.58167952 1.28647478
  0.33868857 0.23494835 0.52111614]]
