In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.20.0'

#**TENSORFLOW CONSTANT**

In [5]:
x=tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [6]:
y=tf.constant(5.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

In [7]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [8]:
tf.config.list_physical_devices('GPU')

[]

In [9]:
z=tf.constant('HIFI')
z

<tf.Tensor: shape=(), dtype=string, numpy=b'HIFI'>

In [10]:
b=tf.constant(True)
b

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [11]:
s=tf.constant([1,2,3,4])
s

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [12]:
import numpy as np

In [13]:
a=np.array([[1,2,3],[4,5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
t_2d=tf.constant([[1,2,3],[4,5,6]])
t_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
t_1d=tf.constant([1,2,3])
t_1d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [16]:
t_3d=tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
t_3d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [17]:
t_4d=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t_4d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

#**TENSORFLOW VARIABLE**

In [18]:
x=tf.Variable(1)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [19]:
x.name

'Variable:0'

In [20]:
y= tf.Variable([1,0,2,3,4,5])
y

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 0, 2, 3, 4, 5], dtype=int32)>

In [21]:
y.name

'Variable:0'

In [22]:
z=tf.Variable(1,name='z')
z

<tf.Variable 'z:0' shape=() dtype=int32, numpy=1>

In [23]:
a=tf.Variable(True,False)
a

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [24]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [25]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

#**CREATE TENSORFLOW VARIABLE WITH DIFFERENT SHAPE**

In [26]:
v_2d=tf.Variable([[1,2],[3,4]])
v_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [27]:
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [28]:
tf.reshape(x,(1,1))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>

In [29]:
y

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 0, 2, 3, 4, 5], dtype=int32)>

In [30]:
y_2d=tf.reshape(y,(3,2))
y_2d

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [2, 3],
       [4, 5]], dtype=int32)>

In [31]:
tf.argmax(v_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [32]:
tf.argmax(y)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [33]:
tf.argmax(y_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [34]:
y_2d1=tf.reshape(y,(2,3))
y_2d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [3, 4, 5]], dtype=int32)>

In [35]:
tf.argmax(y_2d1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [36]:
#change/assign new variale to tensor

In [37]:
x_1 = tf.Variable([1,2,3,4])
x_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [38]:
x_1.assign([4,5,6,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 8], dtype=int32)>

In [39]:
x_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 8], dtype=int32)>

In [40]:
## adding elements through assign operator

x_1.assign_add([5,8,6,9])
x_1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 9, 13, 12, 17], dtype=int32)>

In [41]:
# tf.matrh.multiply
x=tf.constant(([1,2,3,4]))
tf.math.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [42]:
x=tf.ones([1,2]);
y=tf.ones([2,1]);
x*y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [43]:
# tf.math.maximum
x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,0.,2.,5.])
tf.math.maximum(x,y)


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [44]:
x=tf.constant([-5.,0.,0.,0.])
y=tf.constant([-3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [45]:
# tf.math.log
x=tf.constant([0,0.5,1,5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [46]:
# tf.math.log
x=tf.constant([0,0.5,1,5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [47]:
# tf.math.sqrt
x=tf.constant([[4.0],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [48]:
x=tf.constant([[-4.0],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [49]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [50]:
tf.ones((1)) , tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [51]:
tf.compat.v1.disable_eager_execution()

In [56]:
tf.compat.v1.placeholder(tf.float32, shape=(20, 30))

<tf.Tensor 'Placeholder_3:0' shape=(20, 30) dtype=float32>